apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
    {{- include "blog.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "blog.name" . }}
  template:
    metadata:
      labels:
        {{- include "blog.labels" . | nindent 8 }}
      annotations:
        appVersion: {{ .Chart.AppVersion | quote }}
        checksum/config: {{ include (print $.Template.BasePath "/envoy-configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: blog
        image: gcr.io/{{ .Values.project }}/blog:{{ .Values.version }}
        imagePullPolicy: Always
        resources:
          {{- toYaml .Values.envoy.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 80
      - name: envoy
        image: envoyproxy/envoy:{{ .Values.envoy.version }}
        args:
        - -c
        - /etc/envoy/config/envoy.yaml
        ports:
        - name: http
          containerPort: 443
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy/config
        - name: envoy-secrets
          mountPath: /etc/envoy/tls
        resources:
          {{- toYaml .Values.envoy.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 443
        readinessProbe:
          httpGet:
            port: 9901
            path: /ready
      volumes:
      - name: envoy-config
        configMap:
          name: envoy
      - name: envoy-secrets
        secret:
          secretName: envoy
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 99
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: blog
