apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "site.fullname" . }}
  labels:
{{ include "site.labels" . | indent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ include "site.name" . }}
