apiVersion: v1
kind: Service
metadata:
  name: {{ include "site.fullname" . }}
  labels:
{{ include "site.labels" . | indent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.ipAddress }}
  ports:
  - name: http
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: {{ include "site.name" . }}
