steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blog:staging', '-f', 'Dockerfile', '.']
  id: 'blog'
  wait_for: ['-']

images: [
  'gcr.io/$PROJECT_ID/blog:staging'
]

options:
  machineType: 'N1_HIGHCPU_8'
