apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
{{ include "blog.labels" . | indent 4 }}
spec:
  secretName: {{ .Values.certificate.name }}
  issuerRef:
    name: {{ include "blog.fullname" . }}
    kind: ClusterIssuer
  commonName: {{ .Values.certificate.host }}
  dnsNames:
  - {{ .Values.certificate.host }}
