apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
{{ include "blog.labels" . | indent 4 }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - dns01:
        clouddns:
          project : {{ .Values.clusterIssuer.project }}
          serviceAccountSecretRef:
            name: dns
            key: service-account.json
