apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
{{ include "blog.labels" . | indent 4 }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    dns01:
      providers:
      - name: clouddns
        clouddns:
          project : {{ .Values.clusterIssuer.project }}
          serviceAccountSecretRef:
            name: dns
            key: service-account.json
