apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
{{ include "blog.labels" . | indent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "blog.name" . }}
  template:
    metadata:
      labels:
{{ include "blog.labels" . | indent 8 }}
      annotations:
        appVersion: {{ .Chart.AppVersion | quote }}
    spec:
      containers:
        - name: nginx
          image: "gcr.io/nicktravers-site/blog:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          resources:
{{ toYaml .Values.nginx.resources | indent 12 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 99
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
{{ include "blog.labels" . | indent 20 }}
