apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
{{ include "blog.labels" . | indent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ include "blog.name" . }}
