apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
{{ include "blog.labels" . | indent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ include "blog.name" . }}
