FROM gcr.io/cloud-marketplace-containers/google/debian10@sha256:9a4a8331d0626e2b56ababd7e4467b8847ef54809d27e721fba2b4b03073ad02 AS build

RUN apt-get update && \
  apt-get install -y apt-transport-https ca-certificates curl gnupg && \
  \
# Google Cloud
  \
  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
  apt-get update && \
  apt-get install -y google-cloud-sdk && \
  \
# Helm
  \
  echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list && \
  curl https://helm.baltorepo.com/organization/signing.asc | apt-key add - && \
  apt-get update && \
  apt-get install -y helm && \
  \
# jq
  \
  apt-get install -y jq && \
  \
# Digital Ocean utils
  curl -LO https://github.com/digitalocean/doctl/releases/download/v1.77.0/doctl-1.77.0-linux-amd64.tar.gz && \
    tar xzf doctl-1.77.0-linux-amd64.tar.gz && \
    mv doctl /usr/local/bin/ && \
  \
# Cleanup
  \
  rm -rf /var/lib/apt/lists/*

WORKDIR /deploy

ADD run_deploy.sh .

ENTRYPOINT ["./run_deploy.sh"]
