steps:

  # Content build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/content:$REVISION_ID', '-f', 'content/Dockerfile', 'content/']
  id: 'content-build'
  wait_for: ['-']
  # Tag the latest version as :latest.
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/content:$REVISION_ID', 'gcr.io/$PROJECT_ID/content']
  wait_for: ['content-build']

  # Nginx build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx:$REVISION_ID', '-f', 'nginx/Dockerfile', 'nginx/']
  id: 'nginx-build'
  wait_for: ['-']
  # Tag the latest version as :latest.
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/nginx:$REVISION_ID', 'gcr.io/$PROJECT_ID/nginx']
  wait_for: ['nginx-build']

images: [
  'gcr.io/$PROJECT_ID/content:$REVISION_ID',
  'gcr.io/$PROJECT_ID/content:latest',
  'gcr.io/$PROJECT_ID/nginx:$REVISION_ID',
  'gcr.io/$PROJECT_ID/nginx:latest'
  ]
