steps:

  # Content build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/content:$_SHA', '-f', 'content/Dockerfile', 'content/']
  id: 'content-build'
  wait_for: ['-']
  # Tag the latest version as :stage.
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/content:$_SHA', 'gcr.io/$PROJECT_ID/content:stage']
  wait_for: ['content-build']

  # Nginx build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx:$_SHA', '-f', 'nginx/Dockerfile', 'nginx/']
  id: 'nginx-build'
  wait_for: ['-']
  # Tag the latest version as :stage.
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/nginx:$_SHA', 'gcr.io/$PROJECT_ID/nginx:stage']
  wait_for: ['nginx-build']

images: [
  'gcr.io/$PROJECT_ID/content:$_SHA',
  'gcr.io/$PROJECT_ID/content:stage',
  'gcr.io/$PROJECT_ID/nginx:$_SHA',
  'gcr.io/$PROJECT_ID/nginx:stage'
  ]

timeout: 1200s
