apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: "nicktrave-dot-rs"
  labels:
    stable.k8s.psg.io/kcm.class: "default"
spec:
  domain: "nicktrave.rs"
  email: "n.e.travers@gmail.com"
  provider: "googlecloud"
  secretName: "tls-site"
