name: CI

on:
  pull_request:
    branches: main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3.3.0
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Lint
      run: make lint
    - name: Build Docker container
      run: make build-docker
