apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: n.e.travers@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    dns01:
      providers:
      - name: clouddns
        clouddns:
          project: nicktravers-site
          serviceAccountSecretRef:
            name: dns
            key: service-account.json
