apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-cert-manager
  labels:
    app: kube-cert-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: palmstonegames/kube-cert-manager:0.3.1
          args:
            - "-data-dir=/var/lib/cert-manager"
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/service-account.json
            - name: GCE_PROJECT
              value: nicktravers-site
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
            - name: secrets
              mountPath: /secrets
              readOnly: true
        - name: kubectl-proxy
          image: palmstonegames/kubectl-proxy:1.4.0
      volumes:
        - name: data
          gcePersistentDisk:
            pdName: kube-cert-manager-staging
            fsType: ext4
        - name: secrets
          secret:
            secretName: dns
